### ISSUE TITLE
missing escape character in xattr path

### ISSUE THREAD

**Issue by StudioBeneden** [Syphon/Syphon-Transmit#10]
Thank you for making this available! works like a charm in my setup. Jus a really simple remark: the terminal command for quarantining the bundle in the instructions is lacking an escape character in the path: "xattr -cr /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/Syphon\ Transmit.bundle" should be "xattr -cr /Library/Application\ Support/Adobe/Common/Plug-ins/7.0/MediaCore/Syphon\ Transmit.bundle" Just my 2 cts :) thanks again!

**Comment by vade** [comment]
Weird I fixed this in the readme last week. Did you check latest?

**Comment by StudioBeneden** [comment]
:) the readme is ok, its the static info on the releases page: https://github.com/Syphon/Syphon-Transmit/releases

**Comment by vade** [comment]
Ohhhhhhhhhhhhhhhhhh

**Comment by vade** [comment]
Fixed. Thank you! I was so confused :D

**Comment by StudioBeneden** [comment]
YW glad to help out! Your project helps me a lot to do production for multi-screen mapping from AFX in realtime! (I use a lot of NDI, but some tools only have syphon in, this saves me from running an instance of NDI-Syphon and getting confused about my internal video-routing.

![IMG_0666](https://github.com/Syphon/Syphon-Transmit/assets/11541387/01717460-976b-4ed9-878f-4b38ce42e466)

**Comment by vade** [comment]
Awesome! I really love seeing things like this No one ever shares how they use these tools!

Thanks!

**Comment by StudioBeneden** [comment]
that's a pity there's so many nice open source tools out there, anything is possible -even on a budget- if you know what you want to achieve and how to combine the right stuff and hack into the hard work people have already done for you... 

This is a test setup for a larger stage design I'm doing for my music collective, translating the graphics I did for a music video a couple of years ago into a multi-screen live stage design. [https://www.youtube.com/watch?v=DkjUXXL03VQ&ab_channel=CarlodeWijs](url) (btw I was checking your website.. Not hard te tell that you're creating tools out of necessity to drive your own creative works, that's some pretty awesome projects and challenges you've been working on!)
