### ISSUE TITLE
Apple Silicon "damaged file"

### ISSUE THREAD

**Issue by nunowonder** [Syphon/Syphon-Transmit#7]
Hello everybody!
First of all, THANK YOU for making this plugin, because it's something Adobe really needs to rethink, as they took off Syphon from Character Animator 2023.
Ok, so I've downloaded the ZIP file, unzip the "Syphon Transmit.bundle" file to the plugin folder /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/ and after opening Ch2023 for the first time, it said something like the file was damaged. It appeared on a window, but multiple times, until it opened Ch2023, but without Syphon working.

After closing Ch2023 and opening again, it didn't gave me the message again, but Syphon still does not work.

So I wrote on terminal:
xattr -cr /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/Syphon\ Transmit.bundle

but Syphon continues not working.

I tried to erase file, putting it again but it seems nothing works. Am I doing anything wrong?

**Comment by vade** [comment]
Steps to try

1. Erase the file
2. Download the file
3. extract the zip
4. move it
5. run xattr on the file
6. launch Ch2023
7. Ensure you have mercury transmit enabled in preferences, and the plugin is loaded and listed there.

If you dont see it - Quit CH2023 launch `Console.app` and search for Syphon, and then lunch CH2023 again.

**Comment by nunowonder** [comment]
On Ch2023 I can't see the Syphon listed, only monitors and NDI. On Ch2022 I can see Syphon, but well, on Ch2022 it Is supposed to be seen because Adobe didn't took it off.
So, I tried to erase, download again, extract, move, run Xattr, nothing done. The Console.app I don't know what to do with it...

**Comment by vade** [comment]
Lets focus on CH2023

1. Launch CH2023 and hold shift. It should reset plugin cache
2. Please share a screenshot of CH2023 preferences for Mercury Transmit.3. 
3. You must run CH2023 in Pro mode, Live, and ensure that Syphon is enabled for the streaming options
4. Console can be intimidating, but without additional info, literally nothing youre giving me is helpful. So please launch console, hit RUN, and just search for Syphon and see if you see anything related to the plugin.

**Comment by vade** [comment]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/65011/210151250-40f71bc8-b0a4-4755-9970-036f00d51d7c.png">

**Comment by nunowonder** [comment]
Anton, you are THE GREATEST man!!!!

Let me explain: I simply launched with shift key hold, and Live Output suddenly had Syphon Server Transmitter…

And you know what? That bug, it disappeared!!! With your plugin there is no more bug! The bug was this: every time I choose another Scene in Character Animator via Syphon, because I created one Scene with “collide” and other stuff like that, even if I wasn’t choosing that scene, the OBS duplicated source origin and I had to simply go to “Rig” and again to “Stream” in Ch, so OBS “cleaned” duplicated sources and continued working well (imagine this in live streaming, it’s very annoying and can lead you to some seconds of still frames, etc etc). 
It’s nothing I was not doing right, I simply can duplicate this bug with a new file, it’s not my file, I can put this problem happening, because as soon as I have one of the CH scenes with those settings, the bug would appear. 

The GREATEST thing is: with your plugin, this problem don’t exist anymore!!!


So I will write on Github the solution of holding shift, but I just wanted to tell you how THANKFUL I AM with you and your work, and how your plugin is Bug Free (at least for what I’ve seen), and this question I leave this for ourselves, just if you want to explore more, I can show you everything but hey… the problem was inside Ch, your plugin don’t have the problem so, maybe you don’t need to expend time in this.

**Comment by nunowonder** [comment]
Happy New Year!

So after done everything I did in my last post, I simply tried one of the sollutions, that was pressing and holding Shift while launching CH2023, and magically, the Syphon Server Transmitter appeared on Live Output and it's working flawlessly!!!

Thank you SO SO MUCH!

**Comment by vade** [comment]
Awesome that’s great! Happy animating!!! 

   
   

 http://vade.info
