### ISSUE TITLE
Troubleshooting tip missing an escape backslash:

### ISSUE THREAD

**Issue by avclubvids** [Syphon/Syphon-Transmit#9]
The advice on solving the "Plugin Damaged" issue says to run this in Terminal:

`xattr -cr /Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/Syphon\ Transmit.bundle`

however, "Application Support" needs an escape for the space, the doc should say:

`xattr -cr /Library/Application\ Support/Adobe/Common/Plug-ins/7.0/MediaCore/Syphon\ Transmit.bundle`

**Comment by vade** [comment]
Thanks. Good catch. I'll update the readme.
